import type { Report, Finding } from "../../../shared-types";
import { SEVERITY_LABEL, CATEGORY_LABEL } from "../../../shared-types";

/**
 * Severity emoji mapping
 */
const SEVERITY_EMOJI: Record<string, string> = {
  critical: "🔴",
  warning: "🟡",
  info: "🔵",
  success: "🟢",
};

/**
 * Format report as Markdown
 */
export function formatAsMarkdown(report: Report): string {
  const lines: string[] = [];

  // Header
  lines.push("# Frontend Performance Report");
  lines.push("");

  // Meta info
  lines.push("## Overview");
  lines.push("");
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| **URL** | ${report.url} |`);
  lines.push(
    `| **Analyzed** | ${new Date(report.timestamp).toLocaleString()} |`,
  );
  lines.push(`| **Duration** | ${report.duration}ms |`);
  if (report.summary.score !== undefined) {
    lines.push(`| **Score** | ${report.summary.score}/100 |`);
  }
  lines.push("");

  // Headline
  lines.push(`> ${report.summary.headline}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);

  const { bySeverity } = report.summary;
  lines.push(
    `| ${SEVERITY_EMOJI.critical} Critical | ${bySeverity.critical} |`,
  );
  lines.push(`| ${SEVERITY_EMOJI.warning} Warning | ${bySeverity.warning} |`);
  lines.push(`| ${SEVERITY_EMOJI.info} Info | ${bySeverity.info} |`);
  lines.push(`| ${SEVERITY_EMOJI.success} Success | ${bySeverity.success} |`);
  lines.push("");

  // Findings
  if (report.findings.length > 0) {
    lines.push("## Findings");
    lines.push("");

    for (const finding of report.findings) {
      lines.push(formatFinding(finding));
      lines.push("");
    }
  } else {
    lines.push("## Findings");
    lines.push("");
    lines.push("✅ No issues found!");
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by ${report.tool.name} v${report.tool.version}*`);

  return lines.join("\n");
}

/**
 * Format a single finding as Markdown
 */
function formatFinding(finding: Finding): string {
  const lines: string[] = [];
  const emoji = SEVERITY_EMOJI[finding.severity] ?? "⚪";
  const severityLabel = SEVERITY_LABEL[finding.severity];
  const categoryLabel = CATEGORY_LABEL[finding.category];

  // Title
  lines.push(`### ${emoji} ${finding.title}`);
  lines.push("");

  // Metadata
  lines.push(
    `**Severity:** ${severityLabel} | **Category:** ${categoryLabel} | **ID:** \`${finding.id}\``,
  );
  lines.push("");

  // Description
  lines.push(finding.description);
  lines.push("");

  // Impact
  lines.push(`**Impact:** ${finding.impact}`);
  lines.push("");

  // Recommendation
  lines.push(`**Recommendation:** ${finding.recommendation}`);

  if (finding.learnMoreUrl) {
    lines.push("");
    lines.push(`📚 [Learn more](${finding.learnMoreUrl})`);
  }

  return lines.join("\n");
}
